version: '3.7'

services:
  rabbitmq:
    container_name: app-rabbit
    image: rabbitmq:management-alpine
    # Always start after reboot
    restart: always
    environment:
      # - RABBITMQ_DEFAULT_VHOST: "/"
      - RABBITMQ_DEFAULT_USER=
      - RABBITMQ_DEFAULT_PASS=
    ports:
      - "15672:15672"
      - "5672:5672"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

    volumes:
      - ./etc/rabbitmq:/etc/rabbitmq
      - ./rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq-logs:/var/log/rabbitmq/log
    # network_mode: "host"

    # Configuration file directory: /etc/rabbitmq
    # Data storage directory: /var/lib/rabbitmq
    # command: >
    #   bash -c "rabbitmq-plugins enable rabbitmq_management"
    # Log directory: /var/log/rabbitmq
    # importain: rabbitmq-plugins enable rabbitmq_management